/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dx_core_DxCore */

#ifndef _Included_com_dx_core_DxCore
#define _Included_com_dx_core_DxCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dx_core_DxCore
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dx_core_DxCore_create
  (JNIEnv *, jobject);

/*
 * Class:     com_dx_core_DxCore
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_dx_core_DxCore_destroy
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dx_core_DxCore
 * Method:    setContext
 * Signature: (ILjava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dx_core_DxCore_setContext
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_dx_core_DxCore
 * Method:    getFingerPrint
 * Signature: (I[BII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dx_core_DxCore_getFingerPrint
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_dx_core_DxCore
 * Method:    getDllVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dx_core_DxCore_getDllVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_dx_core_DxCore
 * Method:    encode
 * Signature: (I[B[BII)I
 */
JNIEXPORT jint JNICALL Java_com_dx_core_DxCore_encode
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_dx_core_DxCore
 * Method:    decode
 * Signature: (I[B[BII)I
 */
JNIEXPORT jint JNICALL Java_com_dx_core_DxCore_decode
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
